//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineTicketOffice.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AirlineTicketOffice.Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllPassengerView.
        /// </summary>
        internal static string AllPassengerViewKey {
            get {
                return ResourceManager.GetString("AllPassengerViewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoughtTicketView.
        /// </summary>
        internal static string BoughtTicketViewKey {
            get {
                return ResourceManager.GetString("BoughtTicketViewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CashierView.
        /// </summary>
        internal static string CashierViewKey {
            get {
                return ResourceManager.GetString("CashierViewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlightsView.
        /// </summary>
        internal static string FlightsViewKey {
            get {
                return ResourceManager.GetString("FlightsViewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPassengerView.
        /// </summary>
        internal static string NewPassengerViewKey {
            get {
                return ResourceManager.GetString("NewPassengerViewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewTicketView.
        /// </summary>
        internal static string NewTicketViewKey {
            get {
                return ResourceManager.GetString("NewTicketViewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TariffsView.
        /// </summary>
        internal static string TariffsViewKey {
            get {
                return ResourceManager.GetString("TariffsViewKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TicketView.
        /// </summary>
        internal static string TicketViewKey {
            get {
                return ResourceManager.GetString("TicketViewKey", resourceCulture);
            }
        }
    }
}
